spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    #    url: jdbc:mysql://192.168.1.24:3306/df_demo
    #    url: jdbc:mysql://localhost:3306/df_demo_05
    url: jdbc:mysql://192.168.5.22:3306/boen_qms_j10-4?serverTimezone=UTC
    username: root
    #    password: heshan8386
    password: root
server:
  port: 1234
swagger:
  enabled: true
gateway:
  queue:
    target: bg  # 每个服务器指定目标队列，例如“bg”或“cg”
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  mapper-locations: classpath*:xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true