spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    #    url: jdbc:mysql://192.168.1.24:3306/df_demo
    #    url: jdbc:mysql://localhost:3306/df_demo_05
    url: jdbc:mysql://192.168.5.72:3306/df_demo_05?serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
#      location: /Users/dafenqi/Downloads #上传文件临时目录
      max-file-size: 10MB
      max-request-size: 500MB
file:
  upload-dir: /Users/dafenqi/Downloads/uploads/ # 文件上传目录配置，需要修改
server:
  port: 1234
swagger:
  enabled: true
gateway:
    ipconfig: http://192.168.5.75:8089 #需要修改
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  mapper-locations: classpath*:xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true